apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: cluster-ns
  namespace: flux-system
spec:
  interval: 5m
  ref:
    branch: main
  url: https://github.com/razeen-bahadoor/myflux-repo.git